### ISSUE TITLE
Feature discussion: avoiding samtools calls

### ISSUE THREAD

**Issue by matthdsm** [ExaScience/elprep#14]
Hi,

To further improve performance, would it be a good choice to avoid shelling out to samtools by using a go native HTSlib implementation? A quick google search brought https://github.com/biogo/hts to the surface.

Do you suppose it's viable to integrate this into elprep?

Cheers
M

**Comment by pcostanza** [comment]
The biogo hts library is a very nice Go library which we indeed have looked at more closely. Unfortunately, it has a some downsides for our purposes. The two main ones are: (1) It doesn't yet support the CRAM format. (2) The data structures in biogo to represent read alignments would make some filters quite inefficient, for example the filter for replacing the sequence dictionary. This is not to claim that the biogo library is 'bad' in any way, it's just that the emphasis of the two different libraries is on different aspects. (In elPrep, we primarily focus on parallel efficiency.)

We could have used the C version of htslib, but its API is rather complex, and requires using different API calls for different file formats. Since most users will have samtools installed anyway, it seemed more straightforward to us to just call out into samtools, and then parse/write the plain ASCII SAM format.

I hope this helps to understand our choice a bit better.

**Comment by pcostanza** [comment]
Hi,

You may have noticed that we just released 4.0.0 of elPrep. Among its many new features, we actually now added native support for reading and writing BAM files. Because of your suggestions, we actually thought harder about this, and came up with our own multi-threaded implementation for reading and writing BAM files in Go that is very fast and has a significant positive impact on the overall performance of elPrep.

Thanks a lot again for your suggestion, and I hope it's ok it took us so long to react. ;-)

Cheers,
Pascal

**Comment by matthdsm** [comment]
Hi Pascal,

Thanks a lot! We'll be sure to check it out!

Cheers
M

**Comment by matthdsm** [comment]
Hi Pascal,

just FYI, I've updated the bioconda recipe for elprep to the latest version. So v4 can also be installed through conda.

Cheers
M

**Comment by pcostanza** [comment]
Thanks a lot! :-)
