### ISSUE TITLE
Question about the paper

### ISSUE THREAD

**Issue by dolanor** [ExaScience/elprep#21]
I read the article you published about the benchmarking with elPrep in C++, Java and Go.
I'm very interested also to know how fast was each version developed.

I would have used the mailing-list/forum, but I can't send any messages on it.

**Comment by pcostanza** [comment]
We developed the Go version first, then the C++ version, and finally the Java version. We then iterated over the different versions to apply lessons learned from the respective other implementations. The C++ version took by far the longest development time, and was by far the hardest to implement. The Java version took the least development time and was the easiest to implement. This is primarily due to Java's support for parallel streams in its standard library. The Go version took a bit more development time, and was a bit harder to implement, but not significantly. I hope this helps.

**Comment by ciplogic** [comment]
Hello Pascal,

Can you provide even at request the Java version? I am curious not only because you used Java 8, but I am curious if a Java 11 would change things (G1GC improved a lot in the mean time, also there is GraalVM as an optimization engine which may remove some allocations which you may miss). I don't know Go too well but I know Java, so I can investigate it.

Thanks!

**Comment by ciplogic** [comment]
Was asking for Java version, found it:
https://github.com/ExaScience/elprep-bench

**Comment by pcostanza** [comment]
We have used Java 10 in the paper, with G1GC. I believe older Java versions (<= 9) don't compile. Newer Java versions should work.
