### ISSUE TITLE
MapReduce markdup 

### ISSUE THREAD

**Issue by jamesthegiantpeach** [ExaScience/elprep#26]
I’m wanting to use this tool in a mapreduce engine that I use (it’s not Hadoop it’s container based). 

I’m wondering about how I might go about marking duplicates ( similar to Picard markdup) in a sharded manner. Currently, I have a pipeline that bins unmapped reads, maps them, and then merges the mapped bam file. I then shard the bam file into padded bins of 1Mb. I’m wondering if it’s possible to use your markdup tool on individual shards. Do you see any way forward here? Reads are currently sorted by chr coordinate, but maybe sorting by read name makes this possible?

**Comment by caherzee** [comment]
Hi,

One thing you have to keep in mind is that if you choose to split your mapped bam file into arbitrary small bin files before duplicate marking, you will get different results compared to applying the duplicate marking on the full bam file. That is because of how the duplicate marking algorithm works, see our paper for details: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0132868 

elPrep comes with a set of split/filter/merge tools that allow you to split bam files that can be processed independently or in parallel without losing information, i.e. as if one big bam file is being processed. See the section "Split and Merge tools" in the manual.

We use the split/filter/merge commands internally to implement the elprep sfm command. You could use the sfm command as an inspiration to implement your own command where you want to parallelize using mapreduce.

The sfm command has the following flow:

1) set up following temp directories:

	- a temp directory for storing the split BAM files
	- a temp directory for storing the processed split BAM files
	- a temp directory for storing intermediate metrics files generated when processing each of the split files

By default, the sfm command creates all temp directories in the current working directory, but this can be changed with the --tmp-path option.

2) call the elprep split command to split the input BAM file into smaller BAMs using the temp directories from step 1)

3) call the elprep filter command to process each of the split files separately, while using special elprep filter options in case duplicate marking is used:

	- use —mark-optical-duplicates-intermediate with as argument a file in the temp directory for intermediate metrics results created in step 1)  This will tell elPrep to generate an intermediate metrics file for this particular BAM file that can later be merged with other intermediate metrics files. Merging intermediate metrics files is done after processing all split files by a separate command (step 5).

4) merge the processed split BAM files using the elprep merge command
	
5) Merge the intermediate metrics files using the elprep merge-optical-duplicates-metrics

All of the command mentioned here have specific options that may be useful for your case, but they should be documented in the manual. If you are also considering adding BQSR to your pipeline, you should also take a look at the --bqsr-tables-only and --bqsr-apply options.

Please let us know if this works for you. 

Thanks.

**Comment by jnoatak** [comment]
Thanks for so much detail and the great documentation. I have read through most of it, and I think I can use your split, filter, and merge tools to spread the read prep over a few thousand cores. I'll have some more detailed questions later once I have worked through it in more detail. Two questions come to mind though: Is it a requirement to split by natural contigs (chromosomes, or would there be any issue with using split to chunk into 10kb bins? Also, in markdup you use a concurrent hash table for memoization. Is there any issue with each bin having it's own hash table?

**Comment by caherzee** [comment]
Hi,

Splitting into 10k bins is generally a problem for mark duplicates, not just in elPrep, because you risk losing information. It is independent of using a hash table or not. See section "Splitting execution in genomic regions" in our paper https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0132868#sec004. The elPrep split tool uses the contigs  in the header of the bam file to determine how to split up the bam file in smaller files. You can use the --contig-group-size option for grouping contigs together to balance size of the split files. 

If this is still a problem for you, please let us know so we can discuss it in more detail.

Thanks!
