### ISSUE TITLE
Feature request: working with limits on VMEM

### ISSUE THREAD

**Issue by chrisvanrun** [ExaScience/elprep#29]
It would be grand if ElPrep could somehow be made to work with limited virtual memory.

Our cluster consists for 90% of nodes that have ~360GB RAM available. In addition to that we process whole-genome BAM files that are around 90-120X Coverage.

From our ElPrep benchmark we guestimate that ElPrep will need between 400~550GB VMEM to run most of our samples. This would negate the runtime benefit because the jobs would spend more time in the shared-cluster queue.

Hence a feature request to be able to work with limited memory without crashing:
`runtime: out of memory: cannot allocate 8192-byte block`

One could imagine to have ElPrep only start a `sfm` thread if sufficient memory is available and have the limit set via `memory` limit.

I doubt we are the only one that would love to take ElPrep into production but are limited by hardware and are looking for a somewhat grey area in the resources X runtime landscape.

Looking forward to your thoughts on the matter.

Cheers,
Chris

**Comment by pcostanza** [comment]
It’s certainly possible to implement something like this, but it would probably take a lot of effort. Since our list of features we would like to add to elPrep is already quite long, this will probably not get a high priority, though. Frankly speaking, what features get added to elPrep depends primarily on what funding we receive for particular functionality.

We also welcome code contributions to add such features, and are willing to review them.

If you would like to discuss this over the phone, please let us know.

Thanks,
Pascal

**Comment by chrisvanrun** [comment]
Thank you Pascal.

I had hoped it was possibly a moderate to simple implementation. Alas!

> We also welcome code contributions to add such features, and are willing to review them.

A good reason for me to start studying golang =)
