### ISSUE TITLE
How to control compression level of output?

### ISSUE THREAD

**Issue by carlosmag** [ExaScience/elprep#31]
Hi,
Is there a way to control compression level of output, similarly to [picard MarkDuplicates](https://gatk.broadinstitute.org/hc/en-us/articles/360037052812-MarkDuplicates-Picard-#--COMPRESSION_LEVEL)?
Thanks.

**Comment by pcostanza** [comment]
Hi,

Currently, we don't support controlling the compression level. In our experience, the compression is quite good and produces smaller files than some other common tools. (We cannot guarantee this though.) If you want to avoid compression, for example for piping to other tools, it's probably better to use SAM instead of BAM format as output. Can you elaborate why you are asking for this?

Thanks a lot,
Pascal
