### ISSUE TITLE
Encapsulate format conversions into elprep

### ISSUE THREAD

**Issue by vladimirkovacevic** [ExaScience/elprep#33]
Do you have plans to encapsulate format conversions (VCF->elPrep VCF, Fasta->elprep_fasta, BED->ElPrep BED) inside the tool, so the user does not have the overhead of running these commands?
These are standard bioinformatic formats, and additionally keeping these special elprep files could be cumbersome. Thanks :)

**Comment by pcostanza** [comment]
No, we don't have such plans. We came up with our own file formats because they have a significant positive impact on the runtime performance of elPrep. If we would read VCF, FASTA, or BED files directly, elPrep would become slower, in some cases significantly slower, because these file formats are, frankly, not very well designed.

With regard to workflow, the idea is that you convert these files once, and then reuse them for multiple runs of elPrep, rather than convert them repeatedly for each run separately. This will give you the best performance.

I hope this helps.

Best,
Pascal

**Comment by vladimirkovacevic** [comment]
Thank you Pascal for the response. I understand.

**Comment by vladimirkovacevic** [comment]
From the user perspective, the most flexible solution would probably be to support having either one of fasta or elprep_fasta on input.

**Comment by pcostanza** [comment]
It would be difficult to make this work really well, although not impossible. If you are really interested in such a feature and would like to support it, let us know, and we can discuss it.
