### ISSUE TITLE
 elprep split behaviour with/without trailing slash on /path/to/output/

### ISSUE THREAD

**Issue by keithj** [ExaScience/elprep#4]
elPrep version 2.10 (LispWorks pre-compiled distribution)

I think the documentation for `elprep split` could be clearer on the importance of the trailing slash on the `/path/to/output/`. If you omit the trailing slash, everything appears to be written to a single file called e.g.  `/path/to/output.sam`. If the slash is included, then the data are split correctly into the directory.

This could be considered a bug because the non-splitting behaviour is probably not what is intended.

**Comment by caherzee** [comment]
Hi,

On 17 Mar 2015, at 13:41, Keith James <notifications@github.com<mailto:notifications@github.com>> wrote:


elPrep version 2.10 (LispWorks pre-compiled distribution)

i think the documentation could be clearer on the importance of the trailing slash on the /path/to/output/. If you omit the trailing slash, everything appears to be written to a single file called e.g. /path/to/output.sam. If the slash is included, then the data are split correctly into the directory.

This could be considered a bug because the non-splitting behaviour is probably not what is intended.

This is a bug. I have added a check in the user interface to see if the user specified a correct pathname (bucket-sort branch). This will be committed to the main branch shortly.

Thanks for reporting the bug.

Charlotte
