### ISSUE TITLE
coverage vs vcf.gz size discrepancy

### ISSUE THREAD

**Issue by desmodus1984** [ExaScience/elprep#60]
Hi,
I am using elprep to do variant calling of samples with ~10X coverage and the sample using for genome assembly. The vcf of the ~10X samples were on average 5GB and that genome-assembly sample vcf was 2.9GB.
Any ideas of why the samples with ~25 GB reads generated bigger vcf files than the one generated with the 145GB sample?

The code was the same for every sample.
I mapped the reads with bwamem-2 followed by vcf calling with elprep.

elprep sfm PA113.sorted.bam PA113.output.bam --nr-of-threads 28 --tmp-path $TMPDIR \
        --mark-duplicates --mark-optical-duplicates PA113.metrics \
        --sorting-order coordinate \
        --bqsr PA113.recal  \
        --reference /users/PHS0338/jpac1984/data/myse-hapog.elfasta \
        --haplotypecaller PA113.vcf.gz

Does it matter whether the input was bam or sam? or coordinate-sorted or not?

Thanks;

**Comment by caherzee** [comment]
Hi,

It seems possible to me that a larger input bam produces a smaller output vcf compared to a smaller input bam.

Do you suspect there is a bug in elPrep because this outcome makes no sense from a biological perspective in your case?
If so, you could remove the haplotypecaller step from the elprep invocation and try to perform that part with GATK and see what the outcome is? If you find there is a bug, please let us know.

If you pass the --sorting-order coordinate option to elPrep, the tool will sort the input by coordinate order. It is not necessary to pre-sort the input before passing it to elPrep. 

elPrep accepts both bam and sam as inputs. It should normally not matter for the final outcome.

Thanks!

Kind regards,
Charlotte

**Comment by desmodus1984** [comment]
Hi Charlotte,

I wanted to ask you a question.
For the ~5 GB vcf files, I mapped fastq files, while for the ~2 GB vcf from the reference, I mapped reads but in fasta format. Do you think this can explain the size difference, and is okay to use as input a bam from fasta reads or is it better to use a bam from mapped fastq files?

Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by caherzee** [comment]
Hi,

The FASTA and FASTQ formats store different information about sequences. As far as I am aware, FASTA is mostly used for storing reference sequences, whereas the FASTQ format is used for storing reads. 

The FASTQ format stores information such as base quality scores, sequence identifier, etc, which are all used by the mapping algorithm, as well as other downstream analysis algorithms. This information is therefore transferred to the bam files. For example, the quality scores, for which there is one for each base, are also stored in the bam. If you map read stored in FASTA -which I did not know is possible- then you won't have this information and cannot store it in the output bam. Hence that would easily half your output size.

I am not sure it is meaningful to run the mark duplicates/bqsr/haplotype caller pipeline on bams that lack information such as quality scores as the underlying algorithms rely on this information...

Best,
Charlotte

**Comment by desmodus1984** [comment]
Hi,

I was having the same question but as you saw I did the mapping and then the variant calling with the fasta-bam file. I was wondering if that lack of information did get translate and hence the final vcf was much smaller than the other.



Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
